### PR TITLE
hacktoberfest.html

### PR DESCRIPTION
**Pull request by diyawaghmare**

### CODE REVIEW

**Comment by not-cool** [comment]
Your sister drolls over these photos.
Lol
Now I'm confused kis behen ki baat maane

**Comment by diyawaghmare** [comment]
My sister drools all the time because she's always sleeping. And she's the
one who wrote it.😂

**Comment by not-cool** [comment]
Ouh. And I thought it was because she is/was head over heels. 🤤
My bad.

**Comment by diyawaghmare** [comment]
Was is correct. 🤷🏻

**Comment by not-cool** [comment]
Doesn't looks like was to me though. 
But should take your word on this.

**Pull request merged**
